### ISSUE TITLE
How to save the model?

### ISSUE THREAD

**Issue by haibao-yu** [akamaster/pytorch_resnet_cifar10#11]
Hi,

When I set the BasicBlock's option as "A" and save the model with following code:
`torch.save(model,  'test.pkl')`,
here is the error:
"AttributeError: Can't pickle local object 'BasicBlock.__init__.<locals>.<lambda>'"

What's problem?

Thanks!

**Comment by akamaster** [comment]
it is not recommended to save model, you should save model's state instead:
` torch.save(model.state_dict(), 'test.pkl")`
