### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by TiRune** [akamaster/pytorch_resnet_cifar10#16]
Dear Akamaster,

Would you be able to add a License file to your code repository? This makes it easier to use for people in companies :)

I suggest an MIT license, which is the most permissive one can have :)

Regards,
Tijmen

**Comment by PhotonQuantum** [comment]
+1 for this. I'm going to include this implementation in an open source project, but since this model doesn't have a valid license, I can't legally use it in my project, or release my project with this model included.

**Comment by akamaster** [comment]
I'll try to add the license asap, in meantime, you have my permission to use the released code in https://github.com/akamaster/pytorch_resnet_cifar10 and models as you wish, just include my name and link to repo if you are using it in the paper.

**Comment by akamaster** [comment]
@TiRune I have finally added the LIcense file, released under BSD 2-clause. Pure open source!
