### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by BAIDU-USA-GAIT-LEOPARD** [akamaster/pytorch_resnet_cifar10#17]
Thanks for your code and pretrained models. 
But it seems that your pretrained models are not fully saved. When load your pretrained model, we found that the shortcut was not saved in the model. So could you please update your pretrained model?

Thanks a lot.

**Comment by BAIDU-USA-GAIT-LEOPARD** [comment]
or this version implementation is still based on the original paper of resnet, i.e., choice A in the resenet.py?

**Comment by akamaster** [comment]
Pretrained models are of configuration "A". I haven't trained the "B" version, but you can do it on your own.
