### ISSUE TITLE
an issue about resnet implementation

### ISSUE THREAD

**Issue by xiaohua-chen** [akamaster/pytorch_resnet_cifar10#24]
Dear professor,I have two questions.
1、Why it is    line 81:     out += self.shortcut(x)    but not    out += x     

2、For ImageNet/iNaturalist  ResNet paper uses option 'B'.?   For cifar10/cifar100 uses option 'A'.
Not sure if I am understanding this right.

Look forward to your kind advic.

**Comment by akamaster** [comment]
1. Please see #23 and comments within.
2. Your understanding is correct. For ImageNet resnets, the configuration B was used historically. However for CIFAR10, the config A was used in the original paper.
