### ISSUE TITLE
Adding LICENSE

### ISSUE THREAD

**Issue by coallaoh** [akamaster/pytorch_resnet_cifar10#5]
Could you add LICENSE (e.g. MIT) to help people better benefit from your work?
Thank you.

**Comment by akamaster** [comment]
I'm not guru of licensing, but simply use as you with with proper citing.

**Comment by coallaoh** [comment]
Without proper license, we cannot use your code. It's not a matter of citation.
For example, if I use a code that comes without a license (and say I post it on my github or include the snippet in a product from my company), the owner of the code may claim exclusive ownership and sue me.
Thus, without a license added to your repository, I wouldn't risk using your code base.

**Comment by akamaster** [comment]
@coallaoh, I finally managed to add the license. Released under BSD 2-clause, pure open source!
