### ISSUE TITLE
Could you add hash tag in your checkpoint name?

### ISSUE THREAD

**Issue by Gasoonjia** [akamaster/pytorch_resnet_cifar10#7]
Thank you for your great work!
However, the checkpoint file can't be achieved by model_zoo.load_url provided by pytorch due to the illegal file name. 
Here's the detail: https://pytorch.org/docs/stable/model_zoo.html?highlight=load_url#torch.utils.model_zoo.load_url
Would you please change your checkpoint name so that we can get it via model_zoo.load_url?

**Comment by akamaster** [comment]
Thanks a lot for suggestion, I just had time to make this change.
